using DFDS.SmartGate.Application.Validation;
using DFDS.SmartGate.Domain.Locations;
using DFDS.SmartGate.Domain.Visits;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DFDS.SmartGate.Infrastructure.Persistence.Configurations;

/// <summary>
/// Maps <see cref="Movement"/> to <c>visit_movements</c>. Two shadow columns keep request order
/// (<see cref="SequenceProperty"/>, assigned by the repository) and the country part of each location
/// (<see cref="FromCountryProperty"/> / <see cref="ToCountryProperty"/>, generated by PostgreSQL from the UN/LOCODE
/// so it can never drift). All four location columns are indexed for exact-match search.
/// </summary>
internal sealed class MovementConfiguration : IEntityTypeConfiguration<Movement>
{
    /// <summary>Table name.</summary>
    private const string TableName = "visit_movements";

    /// <summary>Shadow foreign key to the owning visit.</summary>
    public const string VisitIdProperty = "VisitId";

    /// <summary>Shadow property holding the zero-based position of the movement in the create request.</summary>
    public const string SequenceProperty = "Sequence";

    /// <summary>Shadow property with the ISO country of <see cref="Movement.From"/>; computed by the database.</summary>
    public const string FromCountryProperty = "FromCountry";

    /// <summary>Shadow property with the ISO country of <see cref="Movement.To"/>; computed by the database.</summary>
    public const string ToCountryProperty = "ToCountry";

    /// <inheritdoc/>
    public void Configure(EntityTypeBuilder<Movement> builder)
    {
        builder.ToTable(TableName);

        builder.HasKey(m => m.Id).HasName("pk_visit_movements");
        builder.Property(m => m.Id).HasColumnName("id").ValueGeneratedNever();

        builder.Property<Guid>(VisitIdProperty).HasColumnName("visit_id").IsRequired();
        builder.Property<int>(SequenceProperty).HasColumnName("sequence").IsRequired();

        builder.Property(m => m.Type).HasColumnName("type").HasConversion<short>().IsRequired();
        builder.Property(m => m.UnitNumber).HasColumnName("unit_number").IsRequired();
        builder.Property(m => m.From).HasColumnName("from_location").IsRequired();
        builder.Property(m => m.To).HasColumnName("to_location").IsRequired();
        builder.Property(m => m.Reference).HasColumnName("reference").HasMaxLength(FieldLimits.ReferenceMaxLength);

        builder.Property<string>(FromCountryProperty)
            .HasColumnName("from_country")
            .HasMaxLength(CountryCode.Length)
            .IsFixedLength()
            .IsRequired()
            .HasComputedColumnSql("left(from_location, 2)", stored: true);

        builder.Property<string>(ToCountryProperty)
            .HasColumnName("to_country")
            .HasMaxLength(CountryCode.Length)
            .IsFixedLength()
            .IsRequired()
            .HasComputedColumnSql("left(to_location, 2)", stored: true);

        builder.HasIndex(VisitIdProperty, SequenceProperty)
            .HasDatabaseName("ix_visit_movements_visit_sequence")
            .IsUnique();

        builder.HasIndex(m => m.From).HasDatabaseName("ix_visit_movements_from_location");
        builder.HasIndex(FromCountryProperty).HasDatabaseName("ix_visit_movements_from_country");
        builder.HasIndex(m => m.To).HasDatabaseName("ix_visit_movements_to_location");
        builder.HasIndex(ToCountryProperty).HasDatabaseName("ix_visit_movements_to_country");
    }
}
