// <auto-generated />
using System;
using System.Collections.Generic;
using DFDS.SmartGate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DFDS.SmartGate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VisitDbContext))]
    partial class VisitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DFDS.SmartGate.Domain.Visits.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("from_location")
                        .IsFixedLength();

                    b.Property<string>("FromCountry")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("from_country")
                        .HasComputedColumnSql("left(from_location, 2)", true)
                        .IsFixedLength();

                    b.Property<string>("Reference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("to_location")
                        .IsFixedLength();

                    b.Property<string>("ToCountry")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("to_country")
                        .HasComputedColumnSql("left(to_location, 2)", true)
                        .IsFixedLength();

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_number");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_visit_movements");

                    b.HasIndex("From")
                        .HasDatabaseName("ix_visit_movements_from_location");

                    b.HasIndex("FromCountry")
                        .HasDatabaseName("ix_visit_movements_from_country");

                    b.HasIndex("To")
                        .HasDatabaseName("ix_visit_movements_to_location");

                    b.HasIndex("ToCountry")
                        .HasDatabaseName("ix_visit_movements_to_country");

                    b.HasIndex("VisitId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_visit_movements_visit_sequence");

                    b.ToTable("visit_movements", (string)null);
                });

            modelBuilder.Entity("DFDS.SmartGate.Domain.Visits.StatusHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("changed_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_visit_status_history");

                    b.HasIndex("VisitId", "ChangedAt")
                        .HasDatabaseName("ix_visit_status_history_visit_changed_at");

                    b.ToTable("visit_status_history", null, t =>
                        {
                            t.HasComment("Append-only audit trail of status changes; UPDATE/DELETE are rejected by trigger.");
                        });
                });

            modelBuilder.Entity("DFDS.SmartGate.Domain.Visits.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<short>("CurrentStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("current_status");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("terminal_id")
                        .IsFixedLength();

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Driver", "DFDS.SmartGate.Domain.Visits.Visit.Driver#Driver", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("LicenseNumber")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("driver_license_number");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("driver_name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("driver_phone");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Truck", "DFDS.SmartGate.Domain.Visits.Visit.Truck#Truck", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Carrier")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("truck_carrier");

                            b1.Property<string>("LicensePlate")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("truck_license_plate");

                            b1.Property<string>("UnitNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("truck_unit_number");
                        });

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.HasIndex("TerminalId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_visits_terminal_created");

                    b.HasIndex("TerminalId", "CreatedBy", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_visits_terminal_created_by_created");

                    b.HasIndex("TerminalId", "CurrentStatus", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_visits_terminal_status_created");

                    b.ToTable("visits", null, t =>
                        {
                            t.HasComment("Truck visits. Rows are retained for 7 years (regulatory); archive/partition by created_at, never delete in-app.");
                        });
                });

            modelBuilder.Entity("DFDS.SmartGate.Domain.Visits.Movement", b =>
                {
                    b.HasOne("DFDS.SmartGate.Domain.Visits.Visit", null)
                        .WithMany("Movements")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visit_movements_visit");
                });

            modelBuilder.Entity("DFDS.SmartGate.Domain.Visits.StatusHistoryEntry", b =>
                {
                    b.HasOne("DFDS.SmartGate.Domain.Visits.Visit", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visit_status_history_visit");
                });

            modelBuilder.Entity("DFDS.SmartGate.Domain.Visits.Visit", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
